run_name: qlearning_v1

learning_rate: 0.05
discount_factor: 0.8
epsilon: 1.0
epsilon_decay: 0.95

episodes: 500
steps_per_episode: 50

policy_path: policies/policy_v1.pkl
results_path: results/results_v1.csv