name: Smart Classroom MLOps Pipeline

on: [push]

jobs:

  test-and-evaluate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install Dependencies
        run: |
          cd server/ai
          pip install -r requirements.txt

      - name: Run Evaluation
        run: |
          cd server/ai
          python evaluate.py

      - name: Generate Plots
        run: |
          cd server/ai
          python plot_results.py