name: Smart Classroom MLOps Pipeline

on: [push]

jobs:
    test-and-evaluate:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v4

            - name: Setup Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.13"

            - name: Install Dependencies
              run: |
                  cd server/ai
                  pip install -r requirements.txt

            - name: Train Model V1
              run: |
                  cd server/ai
                  python train.py --config configs/qlearning_v1.yaml

            - name: Train Model V2
              run: |
                  cd server/ai
                  python train.py --config configs/qlearning_v2.yaml

            - name: Run Evaluation
              run: |
                  cd server/ai
                  python evalualte.py

            - name: Generate Plots
              run: |
                  cd server/ai
                  python plot_results.py

            - name: Upload MLOps Artifacts
              uses: actions/upload-artifact@v4
              with:
                  name: ml-outputs
                  path: |
                      server/ai/policies/*.pkl
                      server/ai/results/*.csv
                      server/ai/plots/*.png
